### PR TITLE
#118 animate main menu

### LINKED ISSUE #118: Animate Main Menu
Animate the main menu screen with holo animations and easing and stuff

### PR DESCRIPTION
**Pull request by yvan674**
All the main menus that exist have now been animated. Closes #118

### CODE REVIEW

**Comment by Ativelox** [comment]
My bad, I just wanted to update this branch with current master but somehow made everything worse, can someone just revert that last commit?

**Comment by fkarg** [comment]
like that or further back?

**Comment by yvan674** [comment]
... what happened in here

**Comment by yvan674** [comment]
i'll revert it back to the last working copy manually

**Comment by yvan674** [comment]
ok i have no idea what to do here best i can think of is to delete this branch and restart on the animations from 0 again because trying to revert anything now makes git think that the old reverts are "new" changes

**Pull request closed without merging**
