### PR TITLE
closes #356 resources

### LINKED ISSUE #356: Update Resources
- show Resources on platform
- make unit movement smoother
- Uncollide units on platforms

### PR DESCRIPTION
**Pull request by fkarg**

### CODE REVIEW

**Comment by yvan674** [comment]
i'll review once this branch has been updated

**Comment by fkarg** [comment]
Okey this was super weird

First I did merge the master in locally (command line) and then the diffs were all gone and now I still had to resolve them o.O

**Comment by fkarg** [comment]
Wow, this merge is brutal. If something breaks, look here.

**Comment by Ativelox** [comment]
what exactly is this PR, what does it add

**Comment by fkarg** [comment]
Okey, so the core is actually that in a small InfoBox below a Platform it is shown what Resources there are on Top of it.

**Comment by Ativelox** [comment]
sorry if I'm understanding this wrong but resources which are on the platform are already shown in the platform info window, right?

**Comment by fkarg** [comment]
Ah yes, but this is separate. This 'Tooltip' always shows, instead of Resources being shown on top of the platforms. (We'd need to uncollide them manually, but this is more efficient and easier, timewise as well).

**Comment by fkarg** [comment]
Just looking over the changes that happened. I'll effectively need to redo my work as a whole. I'll do that tomorrow.

**Pull request closed without merging**
