### PR TITLE
make the FoW more efficient

### PR DESCRIPTION
**Pull request by fkarg**
Now the FoW uses caching for Textures that need to be drawn instead of drawing them anew (polygons with dozen of points). Thus, more efficient

### CODE REVIEW

**Comment by Ativelox** [comment]
the circles were already cached, and could you revert the neo layout again?

**Comment by fkarg** [comment]
sure, and yes, but the drawing itself would have been more inefficient before. Now we just draw a texture instead of 100 Lines separately. This overhead was definitely there.

**Comment by Ativelox** [comment]
One huge improvement for the fow would be to "merge" textures into one big texture without taking the pisxels into consideration that are overlapping. If we were able to do that efficiently then we could easily play the game with thousands of units

**Comment by Ativelox** [comment]
since right now if thousands of units were to stand on the same spot the texture would get drawn 1000 times at the same position, which is extreme overhead

**Comment by fkarg** [comment]
Yes there's quite a bit of performance we can get through several layers of caching, I thought about it a bit. Let's talk about that more tomorrow

**Comment by Ativelox** [comment]
yeah, i was just thinking of the techdemo featuring like 1 own unit and 999 enemy units, thus we don't have a fow problem... 👍

**Comment by yvan674** [comment]
@fkarg what texture did you use and if you used just a circle texture, could you change it to an ellipse that's half as tall as it is wide so that it's isometric?

**Comment by Ativelox** [comment]
agreed with yvan, if we use cached textures now, might aswell use a prettier one that fits the game

**Comment by Ativelox** [comment]
@yvan674 true, that is a way better idea, since we're operating in the same space. Then we could even distort the ellipse by the factor, since I don't know exactly whether 0.5 is the exact factor we would need to use, but that makes things even more easy

**Comment by fkarg** [comment]
It already is a Ellipse

**Comment by fkarg** [comment]
It was from the beginning. You could certainly make that creation more efficient but that really doesn't matter

**Comment by fkarg** [comment]
Okay hab anscheinend irgendwas zerschossen. Bin dran

**Comment by fkarg** [comment]
@Ativelox was male ich wenn ich möchte dass es eben nicht Transparent ist? Weder Weiß noch Schwarz noch sonstwas ich ausprobiert habe scheint einen Effekt zu haben.

**Comment by Ativelox** [comment]
@fkarg alles mit einem alpha channel von 0 (also keine transparenz) sollte funktionieren, vielleicht musst du im AlphaComparator an dem argument ReferenceAlpha schrauben, ich kann mir gut vorstellen dass da für texturen eine 1 hin muss und keine 0, weil 0 besteht auch den alpha test bei keiner transparenz möglicherweise (aber hat doch auch davor funktioniert also schau einfach was du geändert hast)

**Pull request closed without merging**
